---
# addc9.yaml - playbook for adding Cloud9 user to an instance; primarily
# for allowing Cloud9 logins to Gopherbot dev instances

# note: run aws_init first to create the build user

# platform-specific definitions including data volumes
- name: Set platform-specific variables
  import_playbook: platform-vars.yaml

- hosts: "{{ target }}"
  name: Cloud9 User
  become: yes
  remote_user: build
  tasks:
  - name: Remove launch user
    user:
      name: "{{ build_remote }}"
      state: absent
      remove: yes
      force: yes
  - name: Create Users role
    import_role:
      name: ansible-users
  - name: Copy Cloud9 Install script
    copy:
      src: files/c9install.sh
      dest: /usr/local/bin/c9install.sh
      mode: 0755
  - name: Install Cloud9 for Users
    become_user: "{{ item.username }}"
    command: /usr/local/bin/c9install.sh
    args:
      creates: "/home/{{ item.username }}/.c9"
    with_items: "{{ users }}"
  - name: Create User .ssh directory
    file:
      path: "/home/{{ item.username }}/.ssh"
      owner: "{{ item.username }}"
      group: "{{ item.username }}"
      state: directory
      mode: 0700
    with_items: "{{ users }}"
  - name: Install the User's SSH key
    copy:
        src: "files/{{ item.username }}/id_rsa"
        dest: "/home/{{ item.username }}/.ssh/id_rsa"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: 0600
    with_items: "{{ users }}"
  - name: Install the User's SSH config
    copy:
        src: "files/{{ item.username }}/ssh-config"
        dest: "/home/{{ item.username }}/.ssh/config"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: 0600
    with_items: "{{ users }}"
