---
# c9devel.yaml - playbook for creating a LinuxJedi devel bastion from
# an ljbase AMI created with ljstandard.yaml

# note: run aws_init first to create the build user

- hosts: "{{ target }}"
  remote_user: build
  tasks:
  - name: Set mountpoints for a Cloud9 developer instances
    set_fact:
      remote_user: build
      mount_points:
      - dir_name: home
        mount_point: /home
      - dir_name: www
        mount_point: /var/www
      - dir_name: httpconf
        mount_point: /etc/httpd/conf.d
      - dir_name: ssl
        mount_point: /etc/pki
# platform-specific definitions including data volumes
- name: Set platform-specific variables
  import_playbook: platform-vars.yaml

- hosts: "{{ target }}"
  name: Set up data volume, users and Go
  become: yes
  remote_user: build
  tasks:
  - name: Remove launch user
    user:
      name: "{{ build_remote }}"
      state: absent
      remove: yes
      force: yes
  - name: Data Volume role
    import_role:
      name: data_vol_single
  - name: Create Users role
    import_role:
      name: ansible-users

- hosts: "{{ target }}"
  name: Remove build user authorized keys
  become: yes
  remote_user: build
  tasks:
  - file:
      path: /build/.ssh/authorized_keys
      state: absent
  - user:
      name: build
      state: absent
      force: yes
