---
# ljstandard.yaml - playbook for creating the LinuxJedi.org standard AMI

# platform-specific definitions including data volumes
- name: Set platform-specific variables
  import_playbook: platform-vars.yaml

- hosts: "{{ target }}:&dist_Amazon_2"
  become: yes
  remote_user: build
  name: Customize the environment
  tasks:
  - name: Sudo nopasswd for wheel
    lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
  - name: Install EPEL 7 repository
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: latest
  - name: Install EPEL gpg key
    rpm_key:
      state: present
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
  - name: Install extra packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
    - jq
    - python2-pip
    - nodejs
    - rubygem-rdoc
    - git
    - unzip
  - name: Install python modules
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: present
    with_items:
    - { name: 'ansible', version: '2.6.1' }
    - { name: 'dnspython', version: '1.15.0' }
    - { name: 'boto', version: '2.49.0' }
    - { name: 'boto3', version: '1.7.58' }
  - name: Install Amazon Linux Extras topics
    command: amazon-linux-extras install {{ item.topic }}={{ item.version }}
    with_items:
    - { topic: 'python3', version: '3.6.2' }
    - { topic: 'ruby2.4', version: '2.4.4' }
    - { topic: 'php7.2', version: '7.2.5' }
  - name: Install ruby gems
    gem:
      name: "{{ item }}"
      user_install: no
      state: present
    with_items:
    - bundler
  - name: Install ruby-awstools
    unarchive:
      src: https://github.com/lnxjedi/ruby-awstools/archive/master.zip
      dest: /usr/local/lib
      remote_src: yes
      creates: /usr/local/lib/ruby-awstools-master
  - name: Set ownership on rawstools
    file:
      path: /usr/local/lib/ruby-awstools-master
      owner: build
      recurse: yes
  - name: Symlink rawstools binaries
    block:
    - command: ls
      args:
        chdir: /usr/local/lib/ruby-awstools-master/bin
      register: rawsbinaries
    - file:
        path: /usr/local/bin/{{ item }}
        src: /usr/local/lib/ruby-awstools-master/bin/{{ item }}
        state: link
      with_items: "{{ rawsbinaries.stdout_lines }}"
  - name: Update all packages
    yum:
      name: '*'
      state: latest

- hosts: "{{ target }}:&dist_Amazon_2"
  remote_user: build
  name: Install rawstools requirements
  tasks:
  - name: Run bundle install
    command: /usr/local/bin/bundle install
    args:
      chdir: /usr/local/lib/ruby-awstools-master
      creates: /usr/local/share/gems/gems/aws-sdk*