---
- name: Check if /data/{{ item.dir_name }} already exists
  stat: path=/data/{{ item.dir_name }}
  register: datadir
- name: Check if mount directory {{ item.mount_point }} exists
  stat: path={{ item.mount_point }}
  register: mountpoint
- name: Copy original {{ item.mount_point }} to /data/{{ item.dir_name }}
  shell: "cp -a {{ item.mount_point }} /data/{{ item.dir_name }}"
  when: mountpoint.stat.exists and not datadir.stat.exists
  register: copy
- name: Ensure mount point /data/{{ item.dir_name }} exists
  file: path=/data/{{ item.dir_name }} state=directory mode=755
  register: newmount
  when: not datadir.stat.exists
- name: Create mountpoint {{ item.mount_point }} if it doesn't exist
  file: path={{ item.mount_point }} state=directory mode=0775
  when: not mountpoint.stat.exists
- name: Bind Mount /data/{{ item.dir_name }} to {{ item.mount_point }}
  mount: "src=/data/{{ item.dir_name }} name={{ item.mount_point }} fstype=none opts=bind state=mounted"
- name: Restore SELinux Context for {{ item.mount_point }}
  shell: "restorecon -R {{ item.mount_point }}"
  when: '(copy.changed or newmount.changed) and ansible_os_family == "RedHat" and ansible_distribution_major_version >= 7'
