---
- name: Create Partition
  shell: 'echo ",,83" | sfdisk /dev/xvdf'
  args:
    creates: /dev/xvdf1
- name: Wait for Partition
  wait_for:
    path: /dev/xvdf1
- name: Create Filesystem
  filesystem: "fstype={{ new_fs_type }} dev=/dev/xvdf1"
- name: Mount Data Volume
  mount: name=/data src=/dev/xvdf1 fstype={{ new_fs_type }} opts=nodev state=mounted
- name: Set Data Mount Permissions
  file: path=/data mode=0700
- include: copy.yaml
  with_items: "{{ mount_points }}"
